name: Node Exporter Test
on:
  workflow_call:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true

  commitlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional
      - name: Validate PR commits with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.38.0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.8
      - name: Install Charmcraft
        run: sudo snap install charmcraft --classic --channel latest/stable
      - name: Run linters
        run: just lint

  type-check:
    name: Static type checking
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.38.0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.8
      - name: Install Charmcraft
        run: sudo snap install charmcraft --classic --channel latest/stable
      - name: Run tests
        run: just typecheck
  unit:
    name: Unit Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.38.0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.8
      - name: Install Charmcraft
        run: sudo snap install charmcraft --classic --channel latest/stable
      - name: Run Unit Tests
        run: just unit


